#!/bin/bash
tr -cs 'A-Za-z' '[\n*]' < /usr/share/dict/linux.words | tr '[:upper:]' '[:lower:]' | sort -u > sorted.words
tr -cs 'A-Za-z' '[\n*]' < ${1:-/dev/stdin} | tr '[:upper:]' '[:lower:]' | sort -u | comm -23 - sorted.words
